# Generated by Django 5.0.6 on 2025-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=260)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
